BlogWebDemo/Models/Category.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace BlogWebDemo.Models
{
    public partial class Category
    {
        public Category()
        {
            News = new HashSet<News>();
        }

        public int CatId { get; set; }
        public string CatName { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string MetaDesc { get; set; }
        public string MetaKey { get; set; }
        public string Thumb { get; set; }
        public bool Published { get; set; }
        public int? Ordering { get; set; }
        public int? Parents { get; set; }
        public int? Levels { get; set; }
        public string Icon { get; set; }
        public string Cover { get; set; }
        public string Description { get; set; }

        public virtual ICollection<News> News { get; set; }
    }
}

BlogWebDemo/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogWebDemo.Models;
using BlogWebDemo.Helpers;
using PagedList.Core;
using System.IO;

namespace BlogWebDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly dbBlogsContext _context;

        public CategoriesController(dbBlogsContext context)
        {
            _context = context;
        }

        // GET: Admin/Categories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = Utilities.PAGE_SIZE;
            var lsCategories = _context.Categories.OrderByDescending(x => x.CatId);
            PagedList<Category> models = new PagedList<Category>(lsCategories, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Categories/Create
        public IActionResult Create()
        {
            ViewData["DanhMucGoc"] = new SelectList(_context.Categories.Where(x => x.Levels == 1), "CatID", "CatName");
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("CatId,CatName,Title,Alias,MetaDesc,MetaKey,Thumb,Published,Ordering,Parents,Levels,Icon,Cover,Description")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb, Microsoft.AspNetCore.Http.IFormFile fCover, Microsoft.AspNetCore.Http.IFormFile fIcon)
        {
            if (ModelState.IsValid)
            {
               category.Alias = Utilities.ToUrlFriendly(category.CatName);
               if (category.Parents == null)
                {
                    category.Levels = 1;
                }    
               else
                {
                    category.Levels = category.Parents == 0 ? 1 : 2;
                }
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string newName = Utilities.ToUrlFriendly(category.CatName) + "preview_" + extension;
                    category.Thumb = await Utilities.UploadFile(fThumb, @"categories\", newName.ToLower());
                }
                if (fCover != null)
                {
                    string extension = Path.GetExtension(fCover.FileName);
                    string newName = "cover_" + Utilities.ToUrlFriendly(category.CatName) + extension;
                    category.Thumb = await Utilities.UploadFile(fCover, @"covers\", newName.ToLower());
                }
                if (fIcon != null)
                {
                    string extension = Path.GetExtension(fIcon.FileName);
                    string newName = "icon_" + Utilities.ToUrlFriendly(category.CatName) + "preview_" + extension;
                    category.Thumb = await Utilities.UploadFile(fIcon, @"icons\", newName.ToLower());
                }
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatId,CatName,Title,Alias,MetaDesc,MetaKey,Thumb,Published,Ordering,Parents,Levels,Icon,Cover,Description")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb, Microsoft.AspNetCore.Http.IFormFile fCover, Microsoft.AspNetCore.Http.IFormFile fIcon)
        {
            if (id != category.CatId)
            {
                return NotFound();
            }    
            if (ModelState.IsValid)
            {
                try
                {
                    category.Alias = Utilities.ToUrlFriendly(category.CatName);
                    if (category.Parents == null)
                    {
                        category.Levels = 1;
                    }
                    else
                    {
                        category.Levels = category.Parents == 0 ? 1 : 2;
                    }
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string newName = Utilities.ToUrlFriendly(category.CatName) + "preview_" + extension;
                        category.Thumb = await Utilities.UploadFile(fThumb, @"categories\", newName.ToLower());
                    }
                    if (fCover != null)
                    {
                        string extension = Path.GetExtension(fCover.FileName);
                        string newName = "cover_" + Utilities.ToUrlFriendly(category.CatName) + extension;
                        category.Thumb = await Utilities.UploadFile(fCover, @"covers\", newName.ToLower());
                    }
                    if (fIcon != null)
                    {
                        string extension = Path.GetExtension(fIcon.FileName);
                        string newName = "icon_" + Utilities.ToUrlFriendly(category.CatName) + "preview_" + extension;
                        category.Thumb = await Utilities.UploadFile(fIcon, @"icons\", newName.ToLower());
                    }
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CatId == id);
        }
    }
}

BlogWebDemo/Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogWebDemo.Models;

namespace BlogWebDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly dbBlogsContext _context;

        public RolesController(dbBlogsContext context)
        {
            _context = context;
        }

        // GET: Admin/Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Admin/Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Roles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,RoleDescription")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,RoleDescription")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Admin/Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

BlogWebDemo/Areas/Admin/Views/Categories/Create.cshtml
@model BlogWebDemo.Models.Category

@{
    ViewData["Title"] = "TẠO MỚI DANH MỤC";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="slim-pageheader">
    <ol class="breadcrumb slim-breadcrumb">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Categories" asp-action="Index">QUẢN LÝ DANH MỤC</a></li>
        <li class="breadcrumb-item active" aria-current="page">TẠO MỚI</li>
    </ol>
    <h6 class="slim-pagetitle">TẠO MỚI DANH MỤC</h6>
</div><!-- slim-pageheader -->

<div class="section-wrapper">
    <div class="form-layout">
        <form asp-area="Admin" asp-controller="Categories" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="row mg-b-25">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">Category Name: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" asp-for="CatName">
                    </div>
                </div> 
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label class="form-control-label">Category Parent: <span class="tx-danger">*</span></label>
                        <select class="form-control select2" @*asp-for="Parents"*@ asp-items="@ViewBag.DanhMucGoc" required>
                            <option value="0" selected>DANH MỤC GỐC</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">Ordering: <span class="tx-danger">*</span></label>
                        <input class="form-control" value="0" type="number" asp-for="Ordering">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="form-control-label">Description: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" asp-for="Description">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="form-group mg-b-10-force">
                        <label for="form-control-label">Thumbail: <span class="tx-danger">*</span></label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="form-control-label">Cover: <span class="tx-danger">*</span></label>
                        <input name="fCover" type="file" class="form-control-file" asp-for="Cover" />
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="form-group mg-b-10-force">
                        <label for="form-control-label">Icon: <span class="tx-danger">*</span></label>
                        <input name="fIcon" type="file" class="form-control-file" asp-for="Icon" />
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="form-control-label">Status</label><br>
                        <input type="checkbox" asp-for="Published"/><span> Active</span>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="form-control-label">Title: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" asp-for="Title">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="form-control-label">MetaKey: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" asp-for="MetaKey">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="form-control-label">MetaDesc: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" asp-for="MetaDesc">
                    </div>

                    <div class="form-layout-footer">
                        <button class="btn btn-primary bd-0">Submit</button>
                        <button asp-area="Admin" asp-controller="Categories" asp-action="Index" class="btn btn-secondary bd-0">Cancel</button>
                    </div><!-- form-layout-footer -->
                </div>
            </div>
        </form>
    </div><!-- form-layout -->
</div><!-- section-wrapper -->

BlogWebDemo/Areas/Admin/Views/Categories/Delete.cshtml
@model BlogWebDemo.Models.Category

@{
    ViewData["Title"] = "XOÁ DANH MỤC";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="slim-pageheader">
    <ol class="breadcrumb slim-breadcrumb">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Categories" asp-action="Index">QUẢN LÝ DANH MỤC</a></li>
        <li class="breadcrumb-item active" aria-current="page">THÔNG TIN</li>
    </ol>
    <h6 class="slim-pagetitle">XOÁ DANH MỤC: @Model.CatName</h6>
</div><!-- slim-pageheader -->

<div class="section-wrapper mg-t-20">
    <div class="form-layout form-layout-7">
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                ID:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="CatId" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Category Name:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="CatName" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div><!-- col-4 -->
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Title:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Title" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Alias:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Alias" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Title:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Title" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Ordering:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Ordering" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Parents:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Parents" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Levels:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Levels" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                MetaDesc:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="MetaDesc" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                MetaKey:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="MetaKey" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Published:
            </div>
            <div class="col-7 col-sm-8">
                @if (Model.Published == true)
                {
                    <span class="btn badge-primary">Public</span>
                }
                else
                {
                    <span class="btn badge-primary">Public</span>
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Thumbnail:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Thumb))
                {
                    <img width="80" height="80" src="~/images/categories/@Model.Thumb" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Icon:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Icon))
                {
                    <img width="80" height="80" src="~/images/icons/@Model.Icon" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Thumbnail:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Cover))
                {
                    <img width="80" height="80" src="~/images/covers/@Model.Cover" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Description:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Description" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
    </div>
</div>

<div style="text-align:center !important" class="form-layout-footer mg-t-30">
    <form asp-area="Admin" asp-action="Delete" asp-route-id="@Model.CatId">
        <input type="hidden" asp-for="CatId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-area="Admin" asp-controller="Categories" asp-action="Index" class="btn btn-success bd-0">Back</a>
    </form>
</div>

BlogWebDemo/Areas/Admin/Views/Categories/Details.cshtml
@model BlogWebDemo.Models.Category

@{
    ViewData["Title"] = "THÔNG TIN DANH MỤC";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="slim-pageheader">
    <ol class="breadcrumb slim-breadcrumb">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Categories" asp-action="Index">QUẢN LÝ DANH MỤC</a></li>
        <li class="breadcrumb-item active" aria-current="page">THÔNG TIN</li>
    </ol>
    <h6 class="slim-pagetitle">THÔNG TIN DANH MỤC</h6>
</div><!-- slim-pageheader -->

<div class="section-wrapper mg-t-20">
    <div class="form-layout form-layout-7">
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                ID:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="CatId" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Category Name:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="CatName" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div><!-- col-4 -->
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Title:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Title" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Alias:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Alias" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Title:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Title" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Ordering:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Ordering" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Parents:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Parents" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Levels:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Levels" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                MetaDesc:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="MetaDesc" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                MetaKey:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="MetaKey" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Published:
            </div>
            <div class="col-7 col-sm-8">
                @if (Model.Published == true)
                {
                    <span class="btn badge-primary">Public</span>
                }
                else
                {
                    <span class="btn badge-primary">Public</span>
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Thumbnail:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Thumb))
                {
                    <img width="80" height="80" src="~/images/categories/@Model.Thumb" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Icon:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Icon))
                {
                    <img width="80" height="80" src="~/images/icons/@Model.Icon" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Thumbnail:
            </div>
            <div class="col-7 col-sm-8">
                @if (!string.IsNullOrEmpty(Model.Cover))
                {
                    <img width="80" height="80" src="~/images/covers/@Model.Cover" alt="@Model.CatName">
                }
            </div><!-- col-4 -->
        </div>
        <div class="row no-gutters">
            <div class="col-5 col-sm-4">
                Description:
            </div>
            <div class="col-7 col-sm-8">
                <input asp-for="Description" class="form-control" type="text" />
            </div><!-- col-4 -->
        </div>
    </div>
</div>

<div style="text-align:center !important" class="form-layout-footer mg-t-30">
    <a asp-area="Admin" asp-controller="Roles" asp-action="Index" class="btn btn-success bd-0">Back</a>
</div>